# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-18.04-desktop"
  config.vm.box_url = "file://ubuntu-18.04-desktop.box"
  config.vm.network :private_network, ip: "172.16.0.60"


  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--vram", "48"]
  end
end